Новая модель ServiceMedia
photo-booking/backend pull request #18
Opened 2023-09-03 11:51 UTC by dzheronimo

Добавлена модель ServiceMedia для связи услуги и работ мастера который к ней относятся.

2023-09-03 12:02 UTC, Leontiev93 requested changes

2023-09-03 12:02 UTC, Leontiev93 commented on services/models.py
> +    service = models.ForeignKey(Service, on_delete=models.CASCADE, related_name='portfolio')
Почему  related_name='portfolio' ?
если мы создали промежуточную таблицу логично добавить доп информацию в нее. по типу локация съемки. 
проверь ralated name конфликтов не будет ? может стоит миграции сделать сразу ?

2023-09-03 12:08 UTC, dzheronimo commented on services/models.py
> +    service = models.ForeignKey(Service, on_delete=models.CASCADE, related_name='portfolio')
Ну вообще принято имена related давать на имени поля, думал сначала поставить media, но потом подумал, что имея только услугу мы можем взять инфо не только по фотке/видео но и пользователе. То есть проще говоря, ссылка ведет не на конкретную работу, а на страницу портфолио мастера. Но это мои мысли, мне кажется так читать будет проще.  А вот локацию добавлять мне кажется будет логичнее в модели MediaFile. Не зависимо от того какая услуга, локация то не поменяется, можно сразу добавить. Нам нужна такая инфо ? Не видел на макетах

2023-09-03 12:09 UTC, dzheronimo commented on services/models.py
> +    service = models.ForeignKey(Service, on_delete=models.CASCADE, related_name='portfolio')
Проще говоря это просто таблица для связи, здесь кроме ID конкретных моделей лучше не пихать.

2023-09-03 12:10 UTC, dzheronimo commented on services/models.py
> +    service = models.ForeignKey(Service, on_delete=models.CASCADE, related_name='portfolio')
Конфликтов нет, проверил
Миграции давай сделаю

2023-09-04 06:03 UTC, VladislavCR commented on services/models.py
> +    service = models.ForeignKey(Service, on_delete=models.CASCADE, related_name='portfolio')
![image](https://github.com/photo-booking/backend/assets/108588125/a2323b9b-cc11-4f01-b9b3-9a3613454867)
я в прошлом пр добавил эту модульку уже)

2023-09-04 06:03 UTC, closed without merging