Feature/users filter
photo-booking/backend pull request #44
Opened 2023-09-15 20:48 UTC by Leontiev93

Добавил Basecomands изменил поля в моделях

2023-09-15 21:53 UTC, Geroy4ik commented on services/management/commands/create_tags.py
> +    help = 'Импорт ингридиентов с json файла'
Ингридиентов?

2023-09-15 21:55 UTC, Geroy4ik approved these changes

2023-09-16 17:07 UTC, VladislavCR requested changes

2023-09-16 17:07 UTC, VladislavCR commented on api/views.py
> +        return Response(status=status.HTTP_200_OK, data={'token:': {token_bd}})
тут должен быть auth_token, видимо pull не сделал последнего обновления 
В конфликтах оставь как было)

2023-09-16 17:07 UTC, VladislavCR commented on api/views.py
> +        return Response(status=status.HTTP_200_OK, data={'token:': {token_bd}})
тоже самое auth_token
return Response(
            status=status.HTTP_200_OK, data={'auth_token': {token_bd}}
        )

2023-09-16 17:07 UTC, VladislavCR commented on services/management/commands/create_tags.py
> +            tags.append(Tag(name=ingredient['name'], slug=ingredient['slug']))
тут тоже ингредиенты вылезли)

2023-09-17 02:40 UTC, VladislavCR approved these changes

2023-09-17 08:12 UTC, Leontiev93 commented on api/views.py
> +        return Response(status=status.HTTP_200_OK, data={'token:': {token_bd}})
Исправил в соответствии с последними твоими изменениями.

2023-09-17 08:12 UTC, Leontiev93 commented on api/views.py
> +        return Response(status=status.HTTP_200_OK, data={'token:': {token_bd}})
Исправил в соответствии с последними твоими изменениями.

2023-09-17 08:14 UTC, merged